#!/bin/bash
set -e

case "$1" in
    remove)
        systemctl daemon-reload
        ;;
    purge)
        rm -f /etc/sharefs.conf
        rm -f /etc/polkit-1/rules.d/90-sharefs-server.rules
        systemctl daemon-reload
        ;;
esac

exit 0
